### ISSUE TITLE
IDP Url for Single Sign On - Bug

### ISSUE THREAD

**Issue by jeffsikes** [flipboxfactory/saml-core#2]
When you are in CraftCMS Admin for the SAML Plugin, looking at My Provider (SP), the Single Logout Service: SLO is showing the Assertion Consumer Service: ACS value (SingleSignOnService) instead of the SLO Url.

I believe it's because the line of code below is incorrect.  When I changed it as seen below, it then displays both the Assertion Consumer Service: ACS value and the Single Logout Service: SLO value correctly in CraftCSM Admin for the SAML Plugin.

https://github.com/flipboxfactory/saml-core/blob/7cb3971c1b034ec04e2d304ee66eec288f08059f/src/controllers/cp/view/metadata/AbstractEditController.php#L269

`
$variables['singleSignOnServices'][$signOnService->getBinding()] = $signOnService->getLocation();
`

**Comment by dsmrt** [comment]
Good catch @jeffsikes ... I'll get a patch going and try and get this up ASAP.

**Comment by dsmrt** [comment]
Update: This is going in RC1. Should be released in the next week or so.

**Comment by dsmrt** [comment]
I have this updated in RC1.
